### ISSUE TITLE
Parallelise LAL waveforms

### ISSUE THREAD

**Issue by GCArullo** [bernuzzi/PyROQ#24]
When activating `parallel=1` with LAL waveforms, the error: `TypeError: can't pickle lal.Dict objects` appears.

**Comment by GCArullo** [comment]
Probably helpful to check what was done e.g. in `bajes`, `gwmodel`, `pyRing` to overcome the issue.
Do the same as [this MR](https://git.ligo.org/lscsoft/pyring/-/merge_requests/10)?

**Comment by GCArullo** [comment]
@matteobreschi here is the LAL issue. Instructions on how to run the test case are [here](https://github.com/bernuzzi/PyROQ#readme).

**Comment by matteobreschi** [comment]
Solved defining `lal.Dict` object inside waveform function
