### ISSUE TITLE
improve parameters managment

### ISSUE THREAD

**Issue by bernuzzi** [bernuzzi/PyROQ#4]
waveform parameters are stored in an list and tracked manually in the original code, including their number. this s bad and needs improvement.

**Comment by bernuzzi** [comment]
Some logic for this is introduced in commit [b445de2d75a8e2593c3b224885eccc4b2f6decb4](https://github.com/bernuzzi/PyROQ/commit/b445de2d75a8e2593c3b224885eccc4b2f6decb4)

**Comment by GCArullo** [comment]
Following the logic introduced by the commit above, the handling of parameters has now been improved and debugged, as of commit 7949200e6d2972474186d258856220226570d9bd.
There are no more hard-coded structures, and the code runs without errors.
